version: '3'
services:
    workstation:
        restart: always
        build: .
        ports:
            - "5000:5000"
        environment:
            AI_PUBLIC_KEY: gQBbBxeWox38mx5h9rmqutCz
            AI_PRIVATE_KEY: ac4W5emzkzZa8WAMdcdv8fdt
            SERVER_PUBLIC_KEY: 3Mwdw6EJmhYDiYZpae3ch8uo
            HTTP_SERVER_URL: "http://192.168.1.3:4000"
            WS_SERVER_URL: "ws://192.168.1.3:4000"
