FROM tensorflow/tensorflow:latest-gpu-py3

ENV PYTHONUNBUFFERED=1

RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update && apt-get install python3.7 -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2

RUN python3 -m pip install pip -U
RUN python3 -m pip install pandas Pillow requests matplotlib numpy
RUN python3 -m pip install --pre gql
RUN python3 -m pip install Django==3.2.4 asyncio django-ipware

EXPOSE 5000

WORKDIR /usr/app/

COPY . .

WORKDIR /usr/app/workstation

RUN python3 manage.py makemigrations connect workgroups
RUN python3 manage.py migrate

CMD ["python3", "manage.py", "runserver", "0:5000"]
