# Generated by Django 3.2.4 on 2021-06-23 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_private_key', models.CharField(max_length=24)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 23, 21, 51, 18, 753369, tzinfo=utc), verbose_name='date')),
            ],
        ),
    ]
