version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      # PRISMA_MANAGEMENT_API_SECRET: mXa8Ghd6ig45nQ
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: mXa8Ghd6ig45nQ
        databases:
          default:
            connector: mongo
            uri: 'mongodb://oshikuru:mk5jeabUhtSmaZ@mongo'
  mongo:
    image: mongo:3.6
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Compass
    # ports:
    # - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: oshikuru
      MONGO_INITDB_ROOT_PASSWORD: mk5jeabUhtSmaZ
    ports:
      - "27017:27017"
    volumes:
      - aibg_mongo:/var/lib/mongo
  game-server:
      build: ./aibg2018
      restart: always
      ports:
        - "9080:9080"
  api:
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      GAME_SERVER_URL: "http://192.168.1.3:9080"
      SERVER_PUBLIC_KEY: 3Mwdw6EJmhYDiYZpae3ch8uo
      SERVER_PRIVATE_KEY: oYBwXDDVKBwTkBaVUv5J3EqM
      AI_PUBLIC_KEY: gQBbBxeWox38mx5h9rmqutCz
      PRISMA_URL: "http://192.168.1.3:4466"
volumes:
  aibg_mongo:
